USE LostArkDB2
GO
INSERT INTO Legaturi_Eliminate
SELECT 'Continents', ContinentID, 'Zones', ZoneID
FROM Zones
WHERE ZoneID NOT IN (
    SELECT MAX(ZoneID)
    FROM Zones
    GROUP BY ContinentID
);

DELETE FROM Zones
WHERE ZoneID NOT IN (
    SELECT MAX(ZoneID)
    FROM Zones
    GROUP BY ContinentID
);
ALTER TABLE Zones
DROP CONSTRAINT PK__Zones__60166795D32CB487
ALTER TABLE Zones
DROP COLUMN ZoneID
ALTER TABLE Zones
ADD CONSTRAINT UQ_ZONES_CONTINENT UNIQUE (ContinentID);

SELECT * FROM Legaturi_Eliminate



