CREATE TABLE Librarii(
	id INT PRIMARY KEY IDENTITY(1,1),
	nume VARCHAR(100) NOT NULL,
	adresa VARCHAR(100) NOT NULL
);

CREATE TABLE Domenii(
	id INT PRIMARY KEY IDENTITY(1,1),
	descriere VARCHAR(256) NOT NULL
);

CREATE TABLE CARTI(
	id INT PRIMARY KEY IDENTITY(1,1),
	id_domeniu INT NOT NULL FOREIGN KEY REFERENCES Domenii(id) ON DELETE CASCADE,
	titlu VARCHAR(100) NOT NULL
);

CREATE TABLE Carti_Librarii(
	id_carte INT NOT NULL FOREIGN KEY REFERENCES CARTI(id),
	id_librarie INT NOT NULL FOREIGN KEY REFERENCES Librarii(id),
	data_achizitie DATE NOT NULL,
	PRIMARY KEY (id_carte,id_librarie)
);

CREATE TABLE Autori(
	id INT PRIMARY KEY IDENTITY(1,1),
	nume VARCHAR(100) NOT NULL,
	prenume VARCHAR(100) NOT NULL
);

CREATE TABLE Autori_Carti(
	id_autor INT NOT NULL FOREIGN KEY REFERENCES Autori(id) ON DELETE CASCADE,
	id_carte INT NOT NULL FOREIGN KEY REFERENCES Carti(id) ON DELETE CASCADE,
	PRIMARY KEY (id_autor,id_carte)
);

