
CREATE TABLE Tipuri(
	id INT PRIMARY KEY IDENTITY(1,1),
	descriere VARCHAR(100) NOT NULL
);

CREATE TABLE Trenuri(
	id INT PRIMARY KEY IDENTITY(1,1),
	tip INT FOREIGN KEY REFERENCES Tipuri(id) ON DELETE CASCADE,
	nume VARCHAR(100)
);

CREATE TABLE Statii(
	id INT PRIMARY KEY IDENTITY(1,1),
	nume VARCHAR(100) NOT NULL
);

CREATE TABLE Ruta(
	id INT PRIMARY KEY IDENTITY(1,1),
	tren_id INT FOREIGN KEY REFERENCES Trenuri(id) ON DELETE CASCADE,
	nume VARCHAR(100) NOT NULL
);

CREATE TABLE Rute_Statii(
	ruta_id INT FOREIGN KEY REFERENCES Ruta(id) ON DELETE CASCADE,
	statie_id INT FOREIGN KEY REFERENCES Statii(id) ON DELETE CASCADE,
	PRIMARY KEY (ruta_id,statie_id),
	ora_sosire TIME NOT NULL,
	ora_plecare TIME NOT NULL,
);
